### ISSUE TITLE
Can I set title for each page?

### ISSUE THREAD

**Issue by gabimladin** [codechips/svelte-pagejs#2]
On the official page of the library, [page.js](https://visionmedia.github.io/page.js/#contexttitle) says you can change the title with Context#title.
> Context#title
> The pushState title.

How can I set title for each page?
```
<Route path="/" component={Home} {data} />
<Route path="/about" component={About} />
<Route path="/login" component={Login} />
```

**Comment by flaird** [comment]
There are some ways to do this. I'm new to Svelte.js to this might not be the proper svelte-way of doing things.

In `Route.svelte` export a new variable for `title` like this:
```
....
export let middleware = [];
export let title = "My App";

// page.js params placeholder
let params = {};
...
```
Also register the `title` in the `register`-function like `register({ path, component, middleware, title });` in the same document.

In `Router.svelte` add a line here for setting the `document.title`:
```
const last = route => {
  return function(ctx) {
    $activeRoute = { ...route, params: ctx.params };
    document.title = $activeRoute.title;
  };
};
```

Now you should have a functionality to set the title as a prop in the `<Route />` like `<Route title='another title' />` .


If you want to set the title for Routes with dynamic params we can do like this in `App.svelte`:
1. Create a new function: `const setTitle = title => (document.title = title);`
2. Bind the function in your `<Route />` like `<Route path="/blog/:post" component={BlogPost} {setTitle} />` and inside that component use `$$props.setTitle('new title');` to set the title.

@codechips Maybe you can give an answer to what can be a more permanent and svelte-way solution to this? An example in the repo for that would also be nice.

**Comment by codechips** [comment]
@gabimladin can't you set the title in the component itself by using `<svelte:head>` https://svelte.dev/docs#svelte_head?

@flaird are you thinking of only setting the title in this case? If so, I can try to think of a clever way to do that with page.js and add it as an example.

**Comment by flaird** [comment]
I agree with @codechips using the `<svelte:head>` is probably the best way to go about it.

@codechips I overcomplicated this, I see that now.

**Comment by codechips** [comment]
Ok. Closing. Looks like we all agree :smiley:
